In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

# State Vectors (kets or bras)

In [2]:
# Here we begin by creating a Fock qutip.states.basis vacuum state vector |0⟩
# with in a Hilbert space with 5 number states, from 0 to 4:
vac = basis(5, 0)
vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [3]:
# and then create a lowering operator (a^) corresponding to 5 number states
# using the qutip.operators.destroy function:
a = destroy(5)
a

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [4]:
# Now lets apply the destruction operator to our vacuum state vac,
a * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [5]:
# We see that, as expected, the vacuum is transformed to the zero vector.
# A more interesting example comes from using the adjoint of the lowering operator, the raising operator a^†:
a.dag() * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [6]:
# The raising operator has in indeed raised the state vec from the vacuum to the |1⟩ state.
# Instead of using the dagger Qobj.dag() method to raise the state,
# we could have also used the built in qutip.operators.create function to make a raising operator:
c = create(5)
c * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [7]:
# which does the same thing. We can raise the vacuum state more than once by successively apply the raising operator:
c * c * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [8]:
# or just taking the square of the raising operator (a^†)2:
c ** 2 * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]