In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

# State Vectors (kets or bras)

In [2]:
# Here we begin by creating a Fock qutip.states.basis vacuum state vector |0⟩
# with in a Hilbert space with 5 number states, from 0 to 4:
vac = basis(5, 0)
vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [3]:
# and then create a lowering operator (a^) corresponding to 5 number states
# using the qutip.operators.destroy function:
a = destroy(5)
a

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [4]:
# Now lets apply the destruction operator to our vacuum state vac,
a * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [5]:
# We see that, as expected, the vacuum is transformed to the zero vector.
# A more interesting example comes from using the adjoint of the lowering operator, the raising operator a^†:
a.dag() * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [6]:
# The raising operator has in indeed raised the state vec from the vacuum to the |1⟩ state.
# Instead of using the dagger Qobj.dag() method to raise the state,
# we could have also used the built in qutip.operators.create function to make a raising operator:
c = create(5)
c * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [7]:
# which does the same thing. We can raise the vacuum state more than once by successively apply the raising operator:
c * c * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [8]:
# or just taking the square of the raising operator (a^†)2:
c ** 2 * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

In [9]:
# Applying the raising operator twice gives the expected (n+1)^0.5 dependence.
# We can use the product of c∗a to also apply the number operator to the state vector vac:
c * a * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [10]:
# or on the |1⟩ state:
c * a * (c * vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [11]:
# or the |2⟩ state:
c * a * (c**2 * vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [2.82842712]
 [0.        ]
 [0.        ]]

In [12]:
# Notice how in this last example, application of the number operator does not give the expected value n=2,
# but rather 2 * 2^0.5. This is because this last state is not normalized to unity as c|n⟩ = (n+1)^0.5|n+1⟩.
# Therefore, we should normalize our vector first:
c * a * (c**2 * vac).unit()

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]

In [13]:
# Since we are giving a demonstration of using states and operators,
# we have done a lot more work than we should have.
# For example, we do not need to operate on the vacuum state to generate a higher number Fock state.
# Instead we can use the qutip.states.basis (or qutip.states.fock) function to directly obtain the required state:
ket = basis(5, 2)
print(ket)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [14]:
# num(N), Number operator
# Notice how it is automatically normalized. We can also use the built in qutip.operators.num operator:
n = num(5)
print(n)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


In [15]:
# Therefore, instead of c * a * (c ** 2 * vac).unit() we have:
n * ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]

In [16]:
# We can also create superpositions of states:
ket = (basis(5, 0) + basis(5, 1)).unit()
print(ket)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]


In [17]:
# where we have used the qutip.Qobj.unit method to again normalize the state. Operating with the number function again:
n * ket

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]

In [18]:
# We can also create coherent states and squeezed states by applying the qutip.operators.displace 
# and qutip.operators.squeeze functions to the vacuum state:
vac = basis(5, 0)

In [19]:
# Displacement operator (Single-mode)
# displace(N,alpha), N = number of levels in Hilbert space, alpha = complex displacement amplitude.
d = displace(5, 1j)
d

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[ 0.60655682+0.j          0.        +0.60628133j -0.4303874 +0.j
   0.        -0.24104351j  0.14552147+0.j        ]
 [ 0.        +0.60628133j -0.00210288+0.j          0.        +0.43991167j
  -0.45440991+0.j          0.        -0.48208701j]
 [-0.4303874 +0.j          0.        +0.43991167j -0.25430923+0.j
   0.        +0.02744907j -0.74553187+0.j        ]
 [ 0.        -0.24104351j -0.45440991+0.j          0.        +0.02744907j
  -0.74415115+0.j          0.        +0.42531786j]
 [ 0.14552147+0.j          0.        -0.48208701j -0.74553187+0.j
   0.        +0.42531786j -0.09850161+0.j        ]]

In [20]:
# Squeezing operator (Single-mode)
# squeeze(N, sp), N = number of levels in Hilbert space, sp = squeezing parameter.
s = squeeze(5, 0.25 + 0.25j)
s

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[ 0.96987284+0.j          0.        +0.j          0.16416578-0.16416578j
   0.        +0.j          0.        -0.07379618j]
 [ 0.        +0.j          0.90770572+0.j          0.        +0.j
   0.2967072 -0.2967072j   0.        +0.j        ]
 [-0.16416578-0.16416578j  0.        +0.j          0.78910986+0.j
   0.        +0.j          0.40212239-0.40212239j]
 [ 0.        +0.j         -0.2967072 -0.2967072j   0.        +0.j
   0.90770572+0.j          0.        +0.j        ]
 [ 0.        +0.07379618j  0.        +0.j         -0.40212239-0.40212239j
   0.        +0.j          0.81923702+0.j        ]]

In [21]:
d * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.60655682+0.j        ]
 [ 0.        +0.60628133j]
 [-0.4303874 +0.j        ]
 [ 0.        -0.24104351j]
 [ 0.14552147+0.j        ]]

In [22]:
d * s * vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.65893786+0.08139381j]
 [ 0.10779462+0.51579735j]
 [-0.37567217-0.01326853j]
 [-0.02688063-0.23828775j]
 [ 0.26352814+0.11512178j]]

# Density matrices
One of the main purpose of QuTiP is to explore the dynamics of open quantum systems, where the most general state of a system is not longer a state vector, but rather a density matrix. Since operations on density matrices operate identically to those of vectors, we will just briefly highlight creating and using these structures.

In [23]:
# The simplest density matrix is created by forming the outer-product |ψ⟩⟨ψ| of a ket vector:
ket = basis(5, 2)
ket * ket.dag()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [24]:
# A similar task can also be accomplished via the qutip.states.fock_dm or qutip.states.ket2dm functions:
fock_dm(5, 2)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [25]:
ket2dm(ket)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [26]:
# If we want to create a density matrix with equal classical probability of being found in the |2⟩ or |4⟩ number states
# we can do the following:
0.5 * ket2dm(basis(5, 4)) + 0.5 * ket2dm(basis(5, 2))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]

In [27]:
# or use 0.5 * fock_dm(5, 2) + 0.5 * fock_dm(5, 4).
# There are also several other built-in functions for creating predefined density matrices,
# for example qutip.states.coherent_dm and qutip.states.thermal_dm
# which create coherent state and thermal state density matrices, respectively.

# Coherent density matrix (outer product)
# coherent_dm(N,alpha), alpha = complex number (eigenvalue) for requested coherent state
coherent_dm(5, 1.25)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.20980701 0.26141096 0.23509686 0.15572585 0.13390765]
 [0.26141096 0.32570738 0.29292109 0.19402805 0.16684347]
 [0.23509686 0.29292109 0.26343512 0.17449684 0.1500487 ]
 [0.15572585 0.19402805 0.17449684 0.11558499 0.09939079]
 [0.13390765 0.16684347 0.1500487  0.09939079 0.0854655 ]]

In [28]:
# Thermal density matrix (for n particles)
# thermal_dm(N,n), n = particle number expectation value
thermal_dm(5, 1.25)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.46927974 0.         0.         0.         0.        ]
 [0.         0.26071096 0.         0.         0.        ]
 [0.         0.         0.14483942 0.         0.        ]
 [0.         0.         0.         0.08046635 0.        ]
 [0.         0.         0.         0.         0.04470353]]

In [29]:
# QuTiP also provides a set of distance metrics for determining how close two density matrix distributions are to each other.
# Included are the trace distance qutip.metrics.tracedist,
# fidelity qutip.metrics.fidelity,
# Hilbert-Schmidt distance qutip.metrics.hilbert_dist,
# Bures distance qutip.metrics.bures_dist,
# Bures angle qutip.metrics.bures_angle,
# and quantum Hellinger distance qutip.metrics.hellinger_dist.
x = coherent_dm(5, 1.25)
y = coherent_dm(5, 1.25j)
z = thermal_dm(5, 0.125)

In [30]:
fidelity(x, x)

1.0000000069648771

In [31]:
tracedist(y, y)

0.0

In [32]:
hellinger_dist(y, y)

0.0

In [33]:
# We also know that for two pure states, the trace distance (T) and the fidelity (F) are related by T = (1−F2)^0.5,
# while the quantum Hellinger distance (QHE) between two pure states |ψ⟩ and |ϕ⟩ is given by QHE=(2−2|⟨ψ|ϕ⟩|^2)^0.5
tracedist(y, x)

0.9771565905440509

In [34]:
np.sqrt(1 - fidelity(y, x) ** 2)

0.9771565699651727

In [35]:
# For a pure state and a mixed state, 1−F^2 ≤ T which can also be verified:
1 - fidelity(x, z) ** 2

0.7782890513578029

In [36]:
tracedist(x, z)

0.8559028328862543

# Qubit (two-level) systems
Having spent a fair amount of time on basis states that represent harmonic oscillator states, we now move on to qubit, or two-level quantum systems (for example a spin-1/2). To create a state vector corresponding to a qubit system, we use the same qutip.states.basis, or qutip.states.fock, function with only two levels:

In [37]:
spin = basis(2, 0)

In [38]:
# Now at this point one may ask how this state is different than
# that of a harmonic oscillator in the vacuum state truncated to two energy levels?
vac = basis(2, 0)

In [39]:
# At this stage, there is no difference. This should not be surprising as we called the exact same function twice.
# The difference between the two comes from the action of the spin operators qutip.operators.sigmax,
# qutip.operators.sigmay, qutip.operators.sigmaz, qutip.operators.sigmap, and qutip.operators.sigmam
# on these two-level states.
# For example, if vac corresponds to the vacuum state of a harmonic oscillator, then, as we have already seen,
# we can use the raising operator to get the |1⟩ state:
vac

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [40]:
c = create(2)
c * vac

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [41]:
# For a spin system, the operator analogous to the raising operator is the
# sigma-plus operator qutip.operators.sigmap. Operating on the spin state gives:
spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [42]:
sigmap() * spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]

In [43]:
# Now we see the difference! The qutip.operators.sigmap operator acting on the spin state returns the zero vector.
# Why is this? To see what happened, let us use the qutip.operators.sigmaz operator:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [44]:
sigmaz() * spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [45]:
spin2 = basis(2, 1)

In [46]:
spin2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [47]:
sigmaz() * spin2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]

In [48]:
# The answer is now apparent. Since the QuTiP qutip.operators.sigmaz function
# uses the standard z-basis representation of the sigma-z spin operator,
# the spin state corresponds to the |↑⟩ state of a two-level spin system while spin2 gives the |↓⟩ state.
# Therefore, in our previous example sigmap() * spin, we raised the qubit state
# out of the truncated two-level Hilbert space resulting in the zero state.

In [49]:
# While at first glance this convention might seem somewhat odd, it is in fact quite handy.
# For one, the spin operators remain in the conventional form. Second, when the spin system is in the |↑⟩ state:
sigmaz() * spin

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [50]:
# the non-zero component is the zeroth-element of the underlying matrix
# (remember that python uses c-indexing, and matrices start with the zeroth element).
# The |↓⟩ state therefore has a non-zero entry in the first index position.
# This corresponds nicely with the quantum information definitions of qubit states,
# where the excited |↑⟩ state is label as |0⟩, and the |↓⟩ state by |1⟩.

In [51]:
# If one wants to create spin operators for higher spin systems, then the qutip.operators.jmat function comes in handy.