In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

# The quantum object class

In [2]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [3]:
Qobj([[1],[2],[3],[4],[5]])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [4]:
x = np.array([[1, 2, 3, 4, 5]])
Qobj(x)

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]

In [5]:
r = np.random.rand(4, 4)
Qobj(r)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.40292085 0.18060621 0.8761674  0.22235786]
 [0.63829941 0.58167635 0.40106191 0.55008464]
 [0.78143986 0.10135315 0.27118379 0.01221835]
 [0.6654232  0.88653624 0.34946045 0.1854181 ]]

# States and operators

In [6]:
# Fock state ket vector
# basis(N,m)/fock(N,m), N = number of levels in Hilbert space, m = level containing excitation (0 if no m given)
basis(5,3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [7]:
# Coherent state
# coherent(N,alpha), alpha = complex number (eigenvalue) for requested coherent state
coherent(5,0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [8]:
# Lowering (destruction) operator
# destroy(N), N = number of levels in Hilbert space.
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [9]:
# Pauli Z matrix
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [10]:
# Higher spin operators
# jmat(j,s), j = integer or half-integer representing spin, s = ‘x’, ‘y’, ‘z’, ‘+’, or ‘-‘
jmat(5/2.0,'+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

# Qobj attributes

In [11]:
q = destroy(4)

In [12]:
# List keeping track of shapes for individual components of a multipartite system (for tensor products and partial traces).
q.dims

[[4], [4]]

In [13]:
# Dimensions of underlying data matrix.
q.shape

(4, 4)

# Qobj Math

In [14]:
q = destroy(4)

In [15]:
x = sigmax()

In [16]:
q + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

In [17]:
x * x

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [18]:
q ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

In [19]:
x / np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

# Functions operating on Qobj class

In [20]:
# Fock state ket vector
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [21]:
# Dagger (adjoint)
# Q.dag(), Returns adjoint (dagger) of object.
basis(5, 3).dag()

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 0. 0. 1. 0.]]

In [22]:
# Coherent density matrix (outer product)
# coherent_dm(N,alpha), alpha = complex number (eigenvalue) for requested coherent state
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [23]:
# Diagonal
# Q.diag(), Returns the diagonal elements.
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

In [24]:
# Full
# Q.full(), Returns full (not sparse) array of Q’s data.
coherent_dm(5, 1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

In [25]:
# Norm
# Q.norm(), Returns L2 norm for states, trace norm for operators.
coherent_dm(5, 1).norm()

1.0000000252077326

In [26]:
# Sqrt
# Q.sqrtm(), Matrix sqrt of operator.
coherent_dm(5, 1).sqrtm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.36791119+0.00000000e+00j 0.36774406+0.00000000e+00j
  0.2610544 +0.00000000e+00j 0.14620658+0.00000000e+00j
  0.08826704+0.00000000e+00j]
 [0.36774406+0.00000000e+00j 0.36757705+4.23874181e-11j
  0.26093584+1.25558676e-10j 0.14614018-2.58178591e-10j
  0.08822695-1.20293587e-10j]
 [0.2610544 +0.00000000e+00j 0.26093584+1.25558676e-10j
  0.18523332+3.71925960e-10j 0.10374209-7.64768498e-10j
  0.06263061-3.56329879e-10j]
 [0.14620658+0.00000000e+00j 0.14614018-2.58178591e-10j
  0.10374209-7.64768498e-10j 0.05810197+1.57254647e-09j
  0.035077  +7.32699235e-10j]
 [0.08826704+0.00000000e+00j 0.08822695-1.20293587e-10j
  0.06263061-3.56329879e-10j 0.035077  +7.32699235e-10j
  0.0211765 +3.41387792e-10j]]

In [27]:
# Trace
# Q.tr(), Returns trace of quantum object.
coherent_dm(5, 1).tr()

1.0

In [28]:
# Unit
# Q.unit(), Returns normalized (unit) vector Q/Q.norm().
(basis(4, 2) + basis(4, 1)).unit()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]