In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [3]:
Qobj([[1],[2],[3],[4],[5]])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [4]:
x = np.array([[1, 2, 3, 4, 5]])
Qobj(x)

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]

In [5]:
r = np.random.rand(4, 4)
Qobj(r)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.53381638 0.90586171 0.20757652 0.72371451]
 [0.54772805 0.1612225  0.46016626 0.70085933]
 [0.04271241 0.90636361 0.56837159 0.2500729 ]
 [0.46966445 0.89858893 0.76116578 0.42051022]]